### ISSUE TITLE
您好 我之前用的这个库，现在build一直下载不下来

### ISSUE THREAD

**Issue by donghegit** [GcsSloop/pager-layoutmanager#30]
您好 我之前用的这个库，现在build一直下载不下来   谢谢

**Comment by GcsSloop** [comment]
已经修复

**Comment by chenfd99** [comment]
这个库白天下不下来...

**Comment by chenfd99** [comment]
这个库半天下不下来...

**Comment by donghegit** [comment]
您是？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenfd99 <notifications@github.com&gt;
发送时间: 2019年9月17日 15:42
收件人: GcsSloop/pager-layoutmanager <pager-layoutmanager@noreply.github.com&gt;
抄送: donghegit <912563071@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[GcsSloop/pager-layoutmanager] 您好 我之前用的这个库，现在build一直下载不下来 (#30)

**Comment by donghegit** [comment]
您好 我没有写过这个库



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenfd99 <notifications@github.com&gt;
发送时间: 2019年9月17日 15:42
收件人: GcsSloop/pager-layoutmanager <pager-layoutmanager@noreply.github.com&gt;
抄送: donghegit <912563071@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[GcsSloop/pager-layoutmanager] 您好 我之前用的这个库，现在build一直下载不下来 (#30)




这个库半天下不下来...

**Comment by leonlee0116** [comment]
我也是一直下载不来
请问有什么方法吗
